version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    assignees:
      - "rymsha"
    reviewers:
      - "rymsha"
    target-branch: "next"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "alansemenov"
    reviewers:
      - "alansemenov"
    target-branch: "next"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    assignees:
      - "rymsha"
    reviewers:
      - "rymsha"
    target-branch: "next"
