plugins {
    id 'com.enonic.xp.app'
    id "com.github.node-gradle.node" version '7.1.0'
}

node {
    download = true
    version = '22.16.0'
}

dependencies {
    include xplibs.repo
    include xplibs.node
    include xplibs.context
    include xplibs.content
    include xplibs.portal
    include xplibs.websocket
    include xplibs.event
    include xplibs.io
    include libs.lib.notifications
    include libs.lib.router
    include libs.lib.thymeleaf
    include libs.lib.mustache
}

repositories {
    mavenLocal()
    mavenCentral()
    xp.enonicRepo()
}

tasks.register('lint', NpmTask) {
    dependsOn ( npmInstall )
    group "verification"
    args = ['run', 'lint']
    outputs.upToDateWhen { false }
}

tasks.register('webpack', NodeTask) {
    dependsOn( npmInstall )
    script = file('node_modules/webpack/bin/webpack.js')
}

check.dependsOn( lint )

jar {
    exclude 'assets/fonts/material.icons.woff2'
    exclude 'assets/bundles/css/*.js'
    exclude 'assets/bundles/js/*.css'

    includeEmptyDirs = false
    dependsOn( webpack )
}
