[versions]
notifications = "3.0.0-B1"
router = "4.0.0-B1"
thymeleaf = "3.0.0-B1"
mustache = "3.0.0-B1"

[libraries]
lib-notifications = { module = "com.enonic.lib:lib-notifications", version.ref = "notifications" }
lib-router = { module = "com.enonic.lib:lib-router", version.ref = "router" }
lib-thymeleaf = { module = "com.enonic.lib:lib-thymeleaf", version.ref = "thymeleaf" }
lib-mustache = { module = "com.enonic.lib:lib-mustache", version.ref = "mustache" }
